server {
    listen       443 ssl;
    server_name  fileupload.example.com;

    ssl_certificate /var/fileupload/tls/fileupload.pem;
    ssl_certificate_key /var/fileupload/tls/fileupload.key;

    location / {
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_pass http://127.0.1.1:8888;
    }
}

server {
    listen       443 ssl;
    server_name  auth.priv.example.com;

    ssl_certificate /var/fileupload/tls/auth.pem;
    ssl_certificate_key /var/fileupload/tls/auth.key;
    ssl_trusted_certificate /var/fileupload/tls/ca-clientauth.pem;
    ssl_verify_client on;

    location / {
        proxy_http_version 1.1;
        proxy_pass http://127.0.1.1:8889;
    }
}

server {
    listen       443 ssl;
    server_name  pub.example.com;

    ssl_certificate /var/fileupload/tls/pub.pem;
    ssl_certificate_key /var/fileupload/tls/pub.key;

    root /var/fileupload/public;

    location / {
        try_files $uri =404;
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Origin https://fileupload.example.com;
    }
}

server {
    listen       443 ssl;
    server_name  priv.example.com;

    ssl_certificate /var/fileupload/tls/priv.pem;
    ssl_certificate_key /var/fileupload/tls/priv.key;

    root /var/fileupload/private;

    location / {
        try_files $uri =404;
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Allow-Origin https://fileupload.example.com;
    }
}
