server {
    listen       443 ssl;
    server_name  fileupload.example.com;

    ssl_certificate /home/example/fileupload/tls/fileupload.pem;
    ssl_certificate_key /home/example/fileupload/tls/fileupload.key;

    location / {
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_pass http://127.0.1.1:8080;
    }
}

server {
    listen       443 ssl;
    server_name  auth.priv.example.com;

    ssl_certificate /home/example/fileupload/tls/auth.pem;
    ssl_certificate_key /home/example/fileupload/tls/auth.key;

    location / {
        proxy_http_version 1.1;
        proxy_pass http://127.0.1.1:8081;
    }
}

server {
    listen       443 ssl;
    server_name  pub.example.com;

    ssl_certificate /home/example/fileupload/tls/pub.pem;
    ssl_certificate_key /home/example/fileupload/tls/pub.key;

    root /home/example/fileupload/public;

    location / {
        try_files $uri =404;
    }
}

server {
    listen       443 ssl;
    server_name  priv.example.com;

    ssl_certificate /home/example/fileupload/tls/priv.pem;
    ssl_certificate_key /home/example/fileupload/tls/priv.key;

    root /home/example/fileupload/private;

    location / {
        try_files $Uri =404;
    }
}
